namespace SoloCrm.Domain.Common;

/// <summary>A country by ISO 3166-1 alpha-2 code with its German and English name.</summary>
public sealed record Country(string Code, string GermanName, string EnglishName);

/// <summary>
/// The fixed list of countries (iteration 5 decision 14): ISO 3166-1 alpha-2 plus <c>XK</c> (Kosovo), ordered by German
/// name. Kept in code instead of relying on ICU data, so that names and lookups are identical in tests and containers.
/// </summary>
public static class Countries
{
    private static readonly Dictionary<string, Country> ByCode;
    private static readonly Dictionary<string, Country> ByName;

    /// <summary>Common names that differ from the official ones (import from other systems).</summary>
    private static readonly (string Alias, string Code)[] Aliases =
    [
        ("USA", "US"),
        ("United States of America", "US"),
        ("UK", "GB"),
        ("Great Britain", "GB"),
        ("Großbritannien", "GB"),
        ("England", "GB"),
        ("Holland", "NL"),
        ("Czech Republic", "CZ"),
        ("Tschechische Republik", "CZ"),
        ("Turkey", "TR"),
        ("Russian Federation", "RU"),
        ("Korea", "KR"),
        ("Macedonia", "MK"),
        ("Mazedonien", "MK"),
    ];

    static Countries()
    {
        ByCode = All.ToDictionary(c => c.Code, StringComparer.OrdinalIgnoreCase);
        ByName = new Dictionary<string, Country>(StringComparer.OrdinalIgnoreCase);
        foreach (var country in All)
        {
            ByName.TryAdd(country.GermanName, country);
            ByName.TryAdd(country.EnglishName, country);
        }

        foreach (var (alias, code) in Aliases)
        {
            ByName.TryAdd(alias, ByCode[code]);
        }
    }

    public static IReadOnlyList<Country> All { get; } =
    [
        new("AF", "Afghanistan", "Afghanistan"),
        new("EG", "Ägypten", "Egypt"),
        new("AX", "Ålandinseln", "Åland Islands"),
        new("AL", "Albanien", "Albania"),
        new("DZ", "Algerien", "Algeria"),
        new("AS", "Amerikanisch-Samoa", "American Samoa"),
        new("VI", "Amerikanische Jungferninseln", "U.S. Virgin Islands"),
        new("UM", "Amerikanische Überseeinseln", "U.S. Outlying Islands"),
        new("AD", "Andorra", "Andorra"),
        new("AO", "Angola", "Angola"),
        new("AI", "Anguilla", "Anguilla"),
        new("AQ", "Antarktis", "Antarctica"),
        new("AG", "Antigua und Barbuda", "Antigua & Barbuda"),
        new("GQ", "Äquatorialguinea", "Equatorial Guinea"),
        new("AR", "Argentinien", "Argentina"),
        new("AM", "Armenien", "Armenia"),
        new("AW", "Aruba", "Aruba"),
        new("AZ", "Aserbaidschan", "Azerbaijan"),
        new("ET", "Äthiopien", "Ethiopia"),
        new("AU", "Australien", "Australia"),
        new("BS", "Bahamas", "Bahamas"),
        new("BH", "Bahrain", "Bahrain"),
        new("BD", "Bangladesch", "Bangladesh"),
        new("BB", "Barbados", "Barbados"),
        new("BY", "Belarus", "Belarus"),
        new("BE", "Belgien", "Belgium"),
        new("BZ", "Belize", "Belize"),
        new("BJ", "Benin", "Benin"),
        new("BM", "Bermuda", "Bermuda"),
        new("BT", "Bhutan", "Bhutan"),
        new("BO", "Bolivien", "Bolivia"),
        new("BA", "Bosnien und Herzegowina", "Bosnia & Herzegovina"),
        new("BW", "Botsuana", "Botswana"),
        new("BV", "Bouvetinsel", "Bouvet Island"),
        new("BR", "Brasilien", "Brazil"),
        new("VG", "Britische Jungferninseln", "British Virgin Islands"),
        new("BN", "Brunei Darussalam", "Brunei"),
        new("BG", "Bulgarien", "Bulgaria"),
        new("BF", "Burkina Faso", "Burkina Faso"),
        new("BI", "Burundi", "Burundi"),
        new("CV", "Cabo Verde", "Cape Verde"),
        new("IO", "Chagos-Archipel", "Chagos Archipelago"),
        new("CL", "Chile", "Chile"),
        new("CN", "China, Festland", "China mainland"),
        new("CK", "Cookinseln", "Cook Islands"),
        new("CR", "Costa Rica", "Costa Rica"),
        new("CI", "Côte d’Ivoire", "Côte d’Ivoire"),
        new("CW", "Curaçao", "Curaçao"),
        new("DK", "Dänemark", "Denmark"),
        new("DE", "Deutschland", "Germany"),
        new("DM", "Dominica", "Dominica"),
        new("DO", "Dominikanische Republik", "Dominican Republic"),
        new("DJ", "Dschibuti", "Djibouti"),
        new("EC", "Ecuador", "Ecuador"),
        new("SV", "El Salvador", "El Salvador"),
        new("ER", "Eritrea", "Eritrea"),
        new("EE", "Estland", "Estonia"),
        new("SZ", "Eswatini", "Eswatini"),
        new("FK", "Falklandinseln", "Falkland Islands"),
        new("FO", "Färöer", "Faroe Islands"),
        new("FJ", "Fidschi", "Fiji"),
        new("FI", "Finnland", "Finland"),
        new("FR", "Frankreich", "France"),
        new("GF", "Französisch-Guayana", "French Guiana"),
        new("PF", "Französisch-Polynesien", "French Polynesia"),
        new("TF", "Französische Süd- und Antarktisgebiete", "French Southern Territories"),
        new("GA", "Gabun", "Gabon"),
        new("GM", "Gambia", "Gambia"),
        new("GE", "Georgien", "Georgia"),
        new("GH", "Ghana", "Ghana"),
        new("GI", "Gibraltar", "Gibraltar"),
        new("GD", "Grenada", "Grenada"),
        new("GR", "Griechenland", "Greece"),
        new("GL", "Grönland", "Greenland"),
        new("GP", "Guadeloupe", "Guadeloupe"),
        new("GU", "Guam", "Guam"),
        new("GT", "Guatemala", "Guatemala"),
        new("GG", "Guernsey", "Guernsey"),
        new("GN", "Guinea", "Guinea"),
        new("GW", "Guinea-Bissau", "Guinea-Bissau"),
        new("GY", "Guyana", "Guyana"),
        new("HT", "Haiti", "Haiti"),
        new("HM", "Heard und McDonaldinseln", "Heard & McDonald Islands"),
        new("HN", "Honduras", "Honduras"),
        new("HK", "Hongkong", "Hong Kong"),
        new("IN", "Indien", "India"),
        new("ID", "Indonesien", "Indonesia"),
        new("IQ", "Irak", "Iraq"),
        new("IR", "Iran", "Iran"),
        new("IE", "Irland", "Ireland"),
        new("IS", "Island", "Iceland"),
        new("IM", "Isle of Man", "Isle of Man"),
        new("IL", "Israel", "Israel"),
        new("IT", "Italien", "Italy"),
        new("JM", "Jamaika", "Jamaica"),
        new("JP", "Japan", "Japan"),
        new("YE", "Jemen", "Yemen"),
        new("JE", "Jersey", "Jersey"),
        new("JO", "Jordanien", "Jordan"),
        new("KY", "Kaimaninseln", "Cayman Islands"),
        new("KH", "Kambodscha", "Cambodia"),
        new("CM", "Kamerun", "Cameroon"),
        new("CA", "Kanada", "Canada"),
        new("BQ", "Karibische Niederlande", "Caribbean Netherlands"),
        new("KZ", "Kasachstan", "Kazakhstan"),
        new("QA", "Katar", "Qatar"),
        new("KE", "Kenia", "Kenya"),
        new("KG", "Kirgisistan", "Kyrgyzstan"),
        new("KI", "Kiribati", "Kiribati"),
        new("CC", "Kokosinseln", "Cocos (Keeling) Islands"),
        new("CO", "Kolumbien", "Colombia"),
        new("KM", "Komoren", "Comoros"),
        new("CG", "Kongo-Brazzaville", "Congo - Brazzaville"),
        new("CD", "Kongo-Kinshasa", "Congo - Kinshasa"),
        new("XK", "Kosovo", "Kosovo"),
        new("HR", "Kroatien", "Croatia"),
        new("CU", "Kuba", "Cuba"),
        new("KW", "Kuwait", "Kuwait"),
        new("LA", "Laos", "Laos"),
        new("LS", "Lesotho", "Lesotho"),
        new("LV", "Lettland", "Latvia"),
        new("LB", "Libanon", "Lebanon"),
        new("LR", "Liberia", "Liberia"),
        new("LY", "Libyen", "Libya"),
        new("LI", "Liechtenstein", "Liechtenstein"),
        new("LT", "Litauen", "Lithuania"),
        new("LU", "Luxemburg", "Luxembourg"),
        new("MO", "Macao", "Macao"),
        new("MG", "Madagaskar", "Madagascar"),
        new("MW", "Malawi", "Malawi"),
        new("MY", "Malaysia", "Malaysia"),
        new("MV", "Malediven", "Maldives"),
        new("ML", "Mali", "Mali"),
        new("MT", "Malta", "Malta"),
        new("MA", "Marokko", "Morocco"),
        new("MH", "Marshallinseln", "Marshall Islands"),
        new("MQ", "Martinique", "Martinique"),
        new("MR", "Mauretanien", "Mauritania"),
        new("MU", "Mauritius", "Mauritius"),
        new("YT", "Mayotte", "Mayotte"),
        new("MX", "Mexiko", "Mexico"),
        new("FM", "Mikronesien", "Micronesia"),
        new("MC", "Monaco", "Monaco"),
        new("MN", "Mongolei", "Mongolia"),
        new("ME", "Montenegro", "Montenegro"),
        new("MS", "Montserrat", "Montserrat"),
        new("MZ", "Mosambik", "Mozambique"),
        new("MM", "Myanmar", "Myanmar (Burma)"),
        new("NA", "Namibia", "Namibia"),
        new("NR", "Nauru", "Nauru"),
        new("NP", "Nepal", "Nepal"),
        new("NC", "Neukaledonien", "New Caledonia"),
        new("NZ", "Neuseeland", "New Zealand"),
        new("NI", "Nicaragua", "Nicaragua"),
        new("NL", "Niederlande", "Netherlands"),
        new("NE", "Niger", "Niger"),
        new("NG", "Nigeria", "Nigeria"),
        new("NU", "Niue", "Niue"),
        new("KP", "Nordkorea", "North Korea"),
        new("MP", "Nördliche Marianen", "Northern Mariana Islands"),
        new("MK", "Nordmazedonien", "North Macedonia"),
        new("NF", "Norfolkinsel", "Norfolk Island"),
        new("NO", "Norwegen", "Norway"),
        new("OM", "Oman", "Oman"),
        new("AT", "Österreich", "Austria"),
        new("PK", "Pakistan", "Pakistan"),
        new("PS", "Palästinensische Autonomiegebiete", "Palestinian Territories"),
        new("PW", "Palau", "Palau"),
        new("PA", "Panama", "Panama"),
        new("PG", "Papua-Neuguinea", "Papua New Guinea"),
        new("PY", "Paraguay", "Paraguay"),
        new("PE", "Peru", "Peru"),
        new("PH", "Philippinen", "Philippines"),
        new("PN", "Pitcairninseln", "Pitcairn Islands"),
        new("PL", "Polen", "Poland"),
        new("PT", "Portugal", "Portugal"),
        new("PR", "Puerto Rico", "Puerto Rico"),
        new("MD", "Republik Moldau", "Moldova"),
        new("RE", "Réunion", "Réunion"),
        new("RW", "Ruanda", "Rwanda"),
        new("RO", "Rumänien", "Romania"),
        new("RU", "Russland", "Russia"),
        new("SB", "Salomonen", "Solomon Islands"),
        new("ZM", "Sambia", "Zambia"),
        new("WS", "Samoa", "Samoa"),
        new("SM", "San Marino", "San Marino"),
        new("ST", "São Tomé und Príncipe", "São Tomé & Príncipe"),
        new("SA", "Saudi-Arabien", "Saudi Arabia"),
        new("SE", "Schweden", "Sweden"),
        new("CH", "Schweiz", "Switzerland"),
        new("SN", "Senegal", "Senegal"),
        new("RS", "Serbien", "Serbia"),
        new("SC", "Seychellen", "Seychelles"),
        new("SL", "Sierra Leone", "Sierra Leone"),
        new("ZW", "Simbabwe", "Zimbabwe"),
        new("SG", "Singapur", "Singapore"),
        new("SX", "Sint Maarten", "Sint Maarten"),
        new("SK", "Slowakei", "Slovakia"),
        new("SI", "Slowenien", "Slovenia"),
        new("SO", "Somalia", "Somalia"),
        new("ES", "Spanien", "Spain"),
        new("SJ", "Spitzbergen und Jan Mayen", "Svalbard & Jan Mayen"),
        new("LK", "Sri Lanka", "Sri Lanka"),
        new("BL", "St. Barthélemy", "St. Barthélemy"),
        new("SH", "St. Helena", "St. Helena"),
        new("KN", "St. Kitts und Nevis", "St. Kitts & Nevis"),
        new("LC", "St. Lucia", "St. Lucia"),
        new("MF", "St. Martin", "St. Martin"),
        new("PM", "St. Pierre und Miquelon", "St. Pierre & Miquelon"),
        new("VC", "St. Vincent und die Grenadinen", "St. Vincent & Grenadines"),
        new("ZA", "Südafrika", "South Africa"),
        new("SD", "Sudan", "Sudan"),
        new("GS", "Südgeorgien und die Südlichen Sandwichinseln", "So. Georgia & So. Sandwich Isl."),
        new("KR", "Südkorea", "South Korea"),
        new("SS", "Südsudan", "South Sudan"),
        new("SR", "Suriname", "Suriname"),
        new("SY", "Syrien", "Syria"),
        new("TJ", "Tadschikistan", "Tajikistan"),
        new("TW", "Taiwan", "Taiwan"),
        new("TZ", "Tansania", "Tanzania"),
        new("TH", "Thailand", "Thailand"),
        new("TL", "Timor-Leste", "Timor-Leste"),
        new("TG", "Togo", "Togo"),
        new("TK", "Tokelau", "Tokelau"),
        new("TO", "Tonga", "Tonga"),
        new("TT", "Trinidad und Tobago", "Trinidad & Tobago"),
        new("TD", "Tschad", "Chad"),
        new("CZ", "Tschechien", "Czechia"),
        new("TN", "Tunesien", "Tunisia"),
        new("TR", "Türkei", "Türkiye"),
        new("TM", "Turkmenistan", "Turkmenistan"),
        new("TC", "Turks- und Caicosinseln", "Turks & Caicos Islands"),
        new("TV", "Tuvalu", "Tuvalu"),
        new("UG", "Uganda", "Uganda"),
        new("UA", "Ukraine", "Ukraine"),
        new("HU", "Ungarn", "Hungary"),
        new("UY", "Uruguay", "Uruguay"),
        new("UZ", "Usbekistan", "Uzbekistan"),
        new("VU", "Vanuatu", "Vanuatu"),
        new("VA", "Vatikanstadt", "Vatican City"),
        new("VE", "Venezuela", "Venezuela"),
        new("AE", "Vereinigte Arabische Emirate", "United Arab Emirates"),
        new("US", "Vereinigte Staaten", "United States"),
        new("GB", "Vereinigtes Königreich", "United Kingdom"),
        new("VN", "Vietnam", "Vietnam"),
        new("WF", "Wallis und Futuna", "Wallis & Futuna"),
        new("CX", "Weihnachtsinsel", "Christmas Island"),
        new("CF", "Zentralafrikanische Republik", "Central African Republic"),
        new("CY", "Zypern", "Cyprus"),
    ];

    public static bool IsValidCode(string? code) => code is { Length: 2 } && ByCode.ContainsKey(code);

    public static Country? ByIsoCode(string? code) => code is null ? null : ByCode.GetValueOrDefault(code.Trim());

    /// <summary>Recognizes a code (<c>DE</c>), a German (<c>Deutschland</c>) or English name (<c>Germany</c>) or an alias.</summary>
    public static Country? Find(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        var trimmed = value.Trim();
        return ByCode.GetValueOrDefault(trimmed) ?? ByName.GetValueOrDefault(trimmed);
    }
}
